project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: "https://danieljamessmith.github.io/portfolio/"
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: Lux
    css: styles.css
    grid: 
      body-width: 1000px
      sidebar-width: 300px
      margin-width: 300px



