project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: "https://danieljamessmith.github.io/portfolio/"
  navbar:
    right:
      - icon: LinkedIn
        text: "LinkedIn"
        href: https://www.linkedin.com/in/danieljames-smith/
      - text: "GitHub Repo"
        href: https://github.com/danieljamessmith/blog
      - about.qmd


format:
  html:
    theme:
      - Lux
      - custom.scss
    css: styles.css
    grid:
      body-width: 1250px

code-block-bg: true
code-block-border-left: "#413764"
highlight-style: atom-one



